os: linux
dist: trusty
# matrix:
#   include:
    # - language: python
language: python
python: 2.7
# addons:
#   apt:
#     packages:
#     - python-pip
install:
  # Install ansible
  - pip install ansible
  # Check ansible version
  - ansible --version
script:
  - cd provision
  - echo localhost > inventory
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook playbook.yml -i inventory --syntax-check
cache:
  pip: true,
  ccache: true